### ISSUE TITLE
No Support of Latest Swift Syntax

### ISSUE THREAD

**Issue by lalxyy** [PandaraWen/PDChart#5]
Why isn't there any support of Swift 2 syntax?
The project is deprecated?

**Comment by lalxyy** [comment]
...A teammate of me is trying to use your code. But I find it hard to solve so many warnings and errors caused by not staying at the latest Swift syntax.

**Comment by PandaraWen** [comment]
Oh sorry, and i will fix it soon

**Comment by PandaraWen** [comment]
@lalxyy The project is updated to be capable for Swift2.2

**Comment by lalxyy** [comment]
Okay thank you. @PandaraWen
